create database testdb;
use testdb;

create table employee (id bigint generated by default as identity, area_of_interest varchar(255), current_designation varchar(255), email_id varchar(255), employee_id bigint, gender varchar(255), name varchar(255), show_without_auth boolean not null, skills varchar(255), years_of_experience integer not null, primary key (id))
create table employee_project_details (id bigint generated by default as identity, achievements varchar(255), employee_email_id varchar(255), employee_id bigint, employee_name varchar(255), from_month tinyint check (from_month between 0 and 11), from_year integer not null, project_description varchar(255), project_id bigint, project_name varchar(255), responsibility varchar(255), roles varchar(255), skills_used varchar(255), to_month tinyint check (to_month between 0 and 11), to_year integer not null, primary key (id))
create table project_details (id bigint generated by default as identity, project_description varchar(255), project_name varchar(255), show_without_auth boolean not null, primary key (id))

INSERT INTO employee (employeeId, name, email_id, gender, current_designation, years_of_experience, area_of_interest, show_without_auth , skill)
VALUES (12345, 'John Doe', 'john.doe@example.com', 'Male', 'Software Engineer', 5, 'Software Development', true, 'Java,Python');

INSERT INTO project_details (project_name, project_description, show_without_auth )
VALUES ('Project A', 'This is the description of Project A', true);

INSERT INTO project_details (project_name, project_description, show_without_auth )
VALUES ('Project B', 'This is the description of Project B', false);

INSERT INTO project_details (project_name, project_description, show_without_auth )
VALUES ('Project C', 'This is the description of Project C', true);

INSERT INTO EmployeeProjectDetails (employee_id, project_id, employee_name , employee_email_id , project_name, project_description, responsibility, roles, achievements, skills_used , from_month , from_year, to_month , to_year)
VALUES (1, 1, 'John Doe', 'john.doe@example.com', 'Project A', 'This is the description of Project A', 'Team Lead', 'Developer', 'Completed project on time', 'Java, Spring', 'January', 2020, 'April', 2021);

INSERT INTO EmployeeProjectDetails (employee_id, project_id, employee_name , employee_email_id , project_name, project_description, responsibility, roles, achievements, skills_used , from_month , from_year, to_month , to_year)
VALUES (2, 1, 'Jane Smith', 'jane.smith@example.com', 'Project A', 'This is the description of Project A', 'Developer', 'Developer', 'Implemented new features', 'Java, Spring', 'March', 2021, 'August', 2021);

INSERT INTO EmployeeProjectDetails (employee_id, project_id, employee_name , employee_email_id , project_name, project_description, responsibility, roles, achievements, skills_used , from_month , from_year, to_month , to_year)
VALUES (1, 2, 'John Doe', 'john.doe@example.com', 'Project B', 'This is the description of Project B', 'Developer', 'Developer', 'Refactored codebase', 'Java, Hibernate', 'June', 2021, 'December', 2021);

